version: 1.0.0
title: goose.nvim custom recipe
description: goose.nvim custom recipe
instructions: |
  <%= instructions %>
prompt: |
  <%= prompt %>
extensions:
- type: builtin
  name: developer
  display_name: Developer Tools
  timeout: 300
  bundled: null